include $(CLEAR_VARS)
LOCAL_MODULE := MiuiCamera
LOCAL_MODULE_OWNER := xiaomi
LOCAL_SRC_FILES := Miui/MiuiCamera.apk
LOCAL_OVERRIDES_PACKAGES := SnapdragonCamera Snap Camera2
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)
